version: '3.8'

services:
  task:
    container_name: task
    image: task:latest
    # Build configuration
    build:      # Context of specified dockerfile is set to the monorepo root to allow us to add package.json from root into dockerfile
      context: ../..
      dockerfile: apps/task/Dockerfile  # Path relative to the context
    environment:
      - PORT=3000              # Environment variable for the port
    ports:
      - "3000:3000"            # Map host port 3000 to container port 3000
    env_file:
      - .env                   # Load environment variables from .env file

