import type { ReactNode } from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import { CssBaseline } from "@mui/material";
import SessionWrapper from "@/contexts/SessionWrapper";
import { SnackbarProvider } from "@/contexts/SnackbarContext";
import GlobalSnackbar from "@/components/GlobalSnackbar";

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <SnackbarProvider>
                {children}
                <GlobalSnackbar />
              </SnackbarProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
